// Lista completa de indicativos telefónicos do mundo (ISO, indicativo, nome PT)
const RAW: [string, string, string][] = [
  ["PT", "+351", "Portugal"],
  ["BR", "+55", "Brasil"],
  ["ES", "+34", "Espanha"],
  ["FR", "+33", "França"],
  ["GB", "+44", "Reino Unido"],
  ["DE", "+49", "Alemanha"],
  ["IT", "+39", "Itália"],
  ["US", "+1", "Estados Unidos"],
  ["AF", "+93", "Afeganistão"],
  ["ZA", "+27", "África do Sul"],
  ["AL", "+355", "Albânia"],
  ["DZ", "+213", "Argélia"],
  ["AD", "+376", "Andorra"],
  ["AO", "+244", "Angola"],
  ["AI", "+1264", "Anguilla"],
  ["AG", "+1268", "Antígua e Barbuda"],
  ["SA", "+966", "Arábia Saudita"],
  ["AR", "+54", "Argentina"],
  ["AM", "+374", "Arménia"],
  ["AW", "+297", "Aruba"],
  ["AU", "+61", "Austrália"],
  ["AT", "+43", "Áustria"],
  ["AZ", "+994", "Azerbaijão"],
  ["BS", "+1242", "Bahamas"],
  ["BH", "+973", "Bahrein"],
  ["BD", "+880", "Bangladesh"],
  ["BB", "+1246", "Barbados"],
  ["BE", "+32", "Bélgica"],
  ["BZ", "+501", "Belize"],
  ["BJ", "+229", "Benim"],
  ["BM", "+1441", "Bermudas"],
  ["BY", "+375", "Bielorrússia"],
  ["BO", "+591", "Bolívia"],
  ["BA", "+387", "Bósnia e Herzegovina"],
  ["BW", "+267", "Botsuana"],
  ["BN", "+673", "Brunei"],
  ["BG", "+359", "Bulgária"],
  ["BF", "+226", "Burquina Faso"],
  ["BI", "+257", "Burundi"],
  ["BT", "+975", "Butão"],
  ["CV", "+238", "Cabo Verde"],
  ["CM", "+237", "Camarões"],
  ["KH", "+855", "Camboja"],
  ["CA", "+1", "Canadá"],
  ["QA", "+974", "Catar"],
  ["KZ", "+7", "Cazaquistão"],
  ["TD", "+235", "Chade"],
  ["CL", "+56", "Chile"],
  ["CN", "+86", "China"],
  ["CY", "+357", "Chipre"],
  ["SG", "+65", "Singapura"],
  ["CO", "+57", "Colômbia"],
  ["KM", "+269", "Comores"],
  ["CG", "+242", "Congo"],
  ["CD", "+243", "Congo (RD)"],
  ["KP", "+850", "Coreia do Norte"],
  ["KR", "+82", "Coreia do Sul"],
  ["CI", "+225", "Costa do Marfim"],
  ["CR", "+506", "Costa Rica"],
  ["HR", "+385", "Croácia"],
  ["CU", "+53", "Cuba"],
  ["CW", "+599", "Curaçao"],
  ["DK", "+45", "Dinamarca"],
  ["DJ", "+253", "Jibuti"],
  ["DM", "+1767", "Dominica"],
  ["EG", "+20", "Egito"],
  ["SV", "+503", "El Salvador"],
  ["AE", "+971", "Emirados Árabes Unidos"],
  ["EC", "+593", "Equador"],
  ["ER", "+291", "Eritreia"],
  ["SK", "+421", "Eslováquia"],
  ["SI", "+386", "Eslovénia"],
  ["EE", "+372", "Estónia"],
  ["SZ", "+268", "Essuatíni"],
  ["ET", "+251", "Etiópia"],
  ["FJ", "+679", "Fiji"],
  ["PH", "+63", "Filipinas"],
  ["FI", "+358", "Finlândia"],
  ["GA", "+241", "Gabão"],
  ["GM", "+220", "Gâmbia"],
  ["GH", "+233", "Gana"],
  ["GE", "+995", "Geórgia"],
  ["GI", "+350", "Gibraltar"],
  ["GD", "+1473", "Granada"],
  ["GR", "+30", "Grécia"],
  ["GL", "+299", "Gronelândia"],
  ["GP", "+590", "Guadalupe"],
  ["GU", "+1671", "Guam"],
  ["GT", "+502", "Guatemala"],
  ["GY", "+592", "Guiana"],
  ["GF", "+594", "Guiana Francesa"],
  ["GN", "+224", "Guiné"],
  ["GQ", "+240", "Guiné Equatorial"],
  ["GW", "+245", "Guiné-Bissau"],
  ["HT", "+509", "Haiti"],
  ["NL", "+31", "Países Baixos"],
  ["HN", "+504", "Honduras"],
  ["HK", "+852", "Hong Kong"],
  ["HU", "+36", "Hungria"],
  ["YE", "+967", "Iémen"],
  ["IN", "+91", "Índia"],
  ["ID", "+62", "Indonésia"],
  ["IR", "+98", "Irão"],
  ["IQ", "+964", "Iraque"],
  ["IE", "+353", "Irlanda"],
  ["IS", "+354", "Islândia"],
  ["IL", "+972", "Israel"],
  ["JM", "+1876", "Jamaica"],
  ["JP", "+81", "Japão"],
  ["JO", "+962", "Jordânia"],
  ["KW", "+965", "Kuwait"],
  ["LA", "+856", "Laos"],
  ["LS", "+266", "Lesoto"],
  ["LV", "+371", "Letónia"],
  ["LB", "+961", "Líbano"],
  ["LR", "+231", "Libéria"],
  ["LY", "+218", "Líbia"],
  ["LI", "+423", "Liechtenstein"],
  ["LT", "+370", "Lituânia"],
  ["LU", "+352", "Luxemburgo"],
  ["MO", "+853", "Macau"],
  ["MK", "+389", "Macedónia do Norte"],
  ["MG", "+261", "Madagáscar"],
  ["MY", "+60", "Malásia"],
  ["MW", "+265", "Maláui"],
  ["MV", "+960", "Maldivas"],
  ["ML", "+223", "Mali"],
  ["MT", "+356", "Malta"],
  ["MA", "+212", "Marrocos"],
  ["MQ", "+596", "Martinica"],
  ["MU", "+230", "Maurícia"],
  ["MR", "+222", "Mauritânia"],
  ["MX", "+52", "México"],
  ["MM", "+95", "Mianmar"],
  ["FM", "+691", "Micronésia"],
  ["MZ", "+258", "Moçambique"],
  ["MD", "+373", "Moldávia"],
  ["MC", "+377", "Mónaco"],
  ["MN", "+976", "Mongólia"],
  ["ME", "+382", "Montenegro"],
  ["MS", "+1664", "Montserrat"],
  ["NA", "+264", "Namíbia"],
  ["NR", "+674", "Nauru"],
  ["NP", "+977", "Nepal"],
  ["NI", "+505", "Nicarágua"],
  ["NE", "+227", "Níger"],
  ["NG", "+234", "Nigéria"],
  ["NO", "+47", "Noruega"],
  ["NC", "+687", "Nova Caledónia"],
  ["NZ", "+64", "Nova Zelândia"],
  ["OM", "+968", "Omã"],
  ["PW", "+680", "Palau"],
  ["PS", "+970", "Palestina"],
  ["PA", "+507", "Panamá"],
  ["PG", "+675", "Papua-Nova Guiné"],
  ["PK", "+92", "Paquistão"],
  ["PY", "+595", "Paraguai"],
  ["PE", "+51", "Peru"],
  ["PF", "+689", "Polinésia Francesa"],
  ["PL", "+48", "Polónia"],
  ["PR", "+1787", "Porto Rico"],
  ["KE", "+254", "Quénia"],
  ["KG", "+996", "Quirguistão"],
  ["KI", "+686", "Kiribati"],
  ["CF", "+236", "República Centro-Africana"],
  ["DO", "+1809", "República Dominicana"],
  ["CZ", "+420", "Chéquia"],
  ["RE", "+262", "Reunião"],
  ["RO", "+40", "Roménia"],
  ["RW", "+250", "Ruanda"],
  ["RU", "+7", "Rússia"],
  ["EH", "+212", "Saara Ocidental"],
  ["WS", "+685", "Samoa"],
  ["AS", "+1684", "Samoa Americana"],
  ["SM", "+378", "São Marino"],
  ["ST", "+239", "São Tomé e Príncipe"],
  ["VC", "+1784", "São Vicente e Granadinas"],
  ["LC", "+1758", "Santa Lúcia"],
  ["KN", "+1869", "São Cristóvão e Neves"],
  ["SN", "+221", "Senegal"],
  ["SL", "+232", "Serra Leoa"],
  ["RS", "+381", "Sérvia"],
  ["SC", "+248", "Seicheles"],
  ["SY", "+963", "Síria"],
  ["SO", "+252", "Somália"],
  ["LK", "+94", "Sri Lanka"],
  ["SD", "+249", "Sudão"],
  ["SS", "+211", "Sudão do Sul"],
  ["SE", "+46", "Suécia"],
  ["CH", "+41", "Suíça"],
  ["SR", "+597", "Suriname"],
  ["TH", "+66", "Tailândia"],
  ["TW", "+886", "Taiwan"],
  ["TJ", "+992", "Tajiquistão"],
  ["TZ", "+255", "Tanzânia"],
  ["TL", "+670", "Timor-Leste"],
  ["TG", "+228", "Togo"],
  ["TO", "+676", "Tonga"],
  ["TT", "+1868", "Trindade e Tobago"],
  ["TN", "+216", "Tunísia"],
  ["TM", "+993", "Turquemenistão"],
  ["TR", "+90", "Turquia"],
  ["TV", "+688", "Tuvalu"],
  ["UA", "+380", "Ucrânia"],
  ["UG", "+256", "Uganda"],
  ["UY", "+598", "Uruguai"],
  ["UZ", "+998", "Usbequistão"],
  ["VU", "+678", "Vanuatu"],
  ["VA", "+379", "Vaticano"],
  ["VE", "+58", "Venezuela"],
  ["VN", "+84", "Vietname"],
  ["VG", "+1284", "Ilhas Virgens Britânicas"],
  ["VI", "+1340", "Ilhas Virgens Americanas"],
  ["ZM", "+260", "Zâmbia"],
  ["ZW", "+263", "Zimbabué"],
  ["KY", "+1345", "Ilhas Caimão"],
  ["FO", "+298", "Ilhas Faroé"],
  ["FK", "+500", "Ilhas Falkland"],
  ["MH", "+692", "Ilhas Marshall"],
  ["SB", "+677", "Ilhas Salomão"],
  ["TC", "+1649", "Ilhas Turcas e Caicos"],
  ["CK", "+682", "Ilhas Cook"],
];

function flag(iso: string) {
  return String.fromCodePoint(...iso.split("").map((c) => 127397 + c.charCodeAt(0)));
}

export type PhoneCountry = { code: string; label: string; search: string };

// Primeiros 8 = mais usados; restantes por ordem alfabética
const PINNED = RAW.slice(0, 8);
const REST = RAW.slice(8).sort((a, b) => a[2].localeCompare(b[2], "pt"));

export const PHONE_COUNTRIES: PhoneCountry[] = [...PINNED, ...REST].map(([iso, code, name]) => ({
  code,
  label: `${flag(iso)} ${name} ${code}`,
  search: `${name} ${code} ${iso}`.toLowerCase(),
}));

// Valores únicos por indicativo (para <Select> que exige value único)
export const PHONE_OPTIONS: PhoneCountry[] = PHONE_COUNTRIES.filter(
  (p, i, arr) => arr.findIndex((x) => x.code === p.code) === i,
);
